new draft blogpost for carbonify
mmmint-ai/mmmint.ai pull request #105
Opened 2021-11-24 10:56 UTC by maximilianstein

2021-11-24 11:24 UTC, MarkWarneke requested changes
Let's talk about this first please

2021-11-24 11:54 UTC, maxleimkuehler commented on drafts/2021-11-25-carbonify-nutzt-Fahrzeugscheinscanner-von-mmmint.ai-zur-Prozessoptimierung.md
> +Das Umweltbundesamt hat eine [gesetzliche Grundlage](https://www.umweltbundesamt.de/themen/verkehr-laerm/kraft-betriebsstoffe/vollzug-38-bimschv-anrechnung-von-strom-fuer#anderungen-ab-dem-verpflicht
...definiert. Dadurch wird es Fahrzeughalter:innen von batteriebetriebene Fahrzeugen (egal ob privat oder gewerblich) ermöglicht, eine Kompensation für die eingesparten Treibhausgase zu beantragen.

2021-11-24 13:52 UTC, Mattis94 approved these changes

2021-11-24 13:52 UTC, Mattis94 commented on drafts/2021-11-25-carbonify-nutzt-Fahrzeugscheinscanner-von-mmmint.ai-zur-Prozessoptimierung.md
> +Das Unternehmen [carbonify.eu](https://www.carbonify.eu/) ermöglicht Unternehmen und Privatpersonen einen simplen Zugang zur Auszahlung der THG-Quote. Damit die Datenverarbeitung der Fahrzeugscheine
z.B.*

2021-11-24 13:52 UTC, Mattis94 commented on drafts/2021-11-25-carbonify-nutzt-Fahrzeugscheinscanner-von-mmmint.ai-zur-Prozessoptimierung.md
> +1. **Lokalisierung relevanter Positionen** Mithilfe eines deep-learning Object Detection Modells werden relevante Positionen ermittelt. Object Detection ist eine Methode aus dem Gebiet Computer Visio
Das Modell ist dabei in einem Transferlearning*

2021-11-26 11:36 UTC, Mattis94 approved these changes

2021-12-06 20:14 UTC, MarkWarneke approved these changes

2021-12-06 20:15 UTC, merged