add bvmw as a partner
mmmint-ai/mmmint.ai pull request #16
Opened 2021-02-03 07:53 UTC by maximilianstein

2021-02-03 07:59 UTC, MarkWarneke requested changes
@maximilianstein glaube das klappt so nicht. Das Logo wird umbrechen und zieht sich dann unter die gesamten Partner.
@Mattis94  wir müssen hier ein wenig das CSS anpassen. 
Können wir das in einem Sprint einplanen? Die ganze Partner UI sieht nicht so gut uas.

[![image](https://user-images.githubusercontent.com/7847915/106715900-fbc42880-65fd-11eb-9d5c-d073cc822db2.png)](https://www.mmmint.ai/about/#partner)

Mobile ists auch Käse

2021-02-03 08:12 UTC, maximilianstein commented
Eilt nicht. @Mattis94 @MarkWarneke

2021-02-03 08:17 UTC, MarkWarneke commented
Added an item https://dev.azure.com/mmmint/mrfiktiv/_backlogs/backlog/mrfiktiv%20Team/Epics/?workitem=270

2021-02-07 19:23 UTC, Mattis94 commented
this mr can be closed, because of https://github.com/mmmint-ai/mmmint.ai/pull/18

2021-02-07 19:23 UTC, closed without merging