Create 2021-07-20-mmmint.ai-Workshop-zu-KI-in-der-Werkstatt.md
mmmint-ai/mmmint.ai pull request #54
Opened 2021-07-15 19:05 UTC by JuliaGin

Test Blogpost

2021-07-15 21:36 UTC, MarkWarneke commented on drafts/2021-07-20-mmmint.ai-Workshop-zu-KI-in-der-Werkstatt.md
> +> mmmint.ai nimmt als Innovationspartners des Innovation-Lab für das KFZ-Gewerbe in Baden-Württemberg einen Platz im Innovationsschaufenster ein und freut sich auf die Möglichkeit spannende KI-Lösung
K&L?

2021-07-16 18:30 UTC, Mattis94 requested changes

2021-07-16 18:30 UTC, Mattis94 commented on drafts/2021-07-20-mmmint.ai-Workshop-zu-KI-in-der-Werkstatt.md
> +  Wir freuen uns einen spannenden Austausch mit namenhaften Herstellern aus der Automobilbranche.
Wir freuen uns auf* einen ...

2021-07-16 18:30 UTC, Mattis94 commented on drafts/2021-07-20-mmmint.ai-Workshop-zu-KI-in-der-Werkstatt.md
> +Die [Zukunftswerkstatt 4.0](https://www.ifa-info.de/zukunftswerkstatt) in Esslingen bei Stuttgart nimmt die Rolle eines „Innovationsschaufensters“ ein, mit dessen Hilfe neue Technologien und Systeme
Der ganze Satz klingt irgendwie unglücklich. Innovationsschaufenster auch sehr gewollt :D

... entlang der Customer Journey* in* Sales und After Sales ...

2021-07-16 18:30 UTC, Mattis94 commented on drafts/2021-07-20-mmmint.ai-Workshop-zu-KI-in-der-Werkstatt.md
> +> mmmint.ai nimmt als Innovationspartners des Innovation-Lab für das KFZ-Gewerbe in Baden-Württemberg einen Platz im Innovationsschaufenster ein und freut sich auf die Möglichkeit spannende KI-Lösung
... nimmt als Innovationspartner* ...

2021-07-16 18:30 UTC, Mattis94 commented on drafts/2021-07-20-mmmint.ai-Workshop-zu-KI-in-der-Werkstatt.md
> +Konzeptionell stellt die Zukunftswerkstatt einen realen Ort dar, an dem die tatsächlichen Strukturen und Prozesse eines Autohausunternehmens realitätsgetreu und praxistauglich abgebildet werden. Als
strategischer* - Adjektiv und so

2021-07-27 08:40 UTC, maxleimkuehler approved these changes

2021-07-31 11:55 UTC, closed without merging

2021-07-31 11:56 UTC, maximilianstein commented
war zu testzwecken