Create 2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-…
mmmint-ai/mmmint.ai pull request #57
Opened 2021-08-01 12:53 UTC by JuliaGin

…bytes-nach-Hannover

2021-08-01 13:10 UTC, MarkWarneke commented on drafts/2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-bytes-nach-Hannover
> +Zwei von unseren Foundern, Maximilian Stein und Max Leimkühler repräsentierten uns auf der Business Stage, als auch in einem interaktiven Workshop.
The indentation is wrong here. See https://raw.githubusercontent.com/mmmint-ai/mmmint.ai/master/_posts/2021-01-15-mmmint-wird-Mitglied-im-ki-bundesverband.md as a reference. 

add two whitespaces.

```suggestion
  Wir waren mit dabei bei der Cars & Bytes 2021, einem von Peppermint Event und Sidney Industries durchgeführten Mobility Summit. Die Messe befasst sich mit allen nur denkbaren Themen rund um die Bereiche Automobil und Mobilität, wie Mobilitätskonzepte, Elektromobilität, Rahmendienstleistungen usw. Diese werden in Form von moderierten Podiumsdiskussionen, interaktiven Workshops und 3D-Exhibits präsentiert.  
  <br/><br/> 
  Zwei von unseren Foundern, Maximilian Stein und Max Leimkühler repräsentierten uns auf der Business Stage, als auch in einem interaktiven Workshop.  
```

Also I think its a bit too long for the excerpt. (The excerpt is displayed in the blog post overview)

2021-08-01 13:13 UTC, Mattis94 requested changes

2021-08-01 13:13 UTC, Mattis94 commented on drafts/2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-bytes-nach-Hannover
> +Die Reihe von abgesagten Automobilmessen und -ausstellungen, wie z.B. der Genfer Salon, New York Autoshow und Motortec Madrid 2020 und dann 2021, bildete ein ernstes Kommunikationsproblem im Automobi
*Die Reihe von abgesagten Automobilmessen und -ausstellungen, wie z.B. der Genfer Salon, die New York Autoshow und die Motortec Madrid 2020  und 2021, bildeten ein bedenkliches Kommunikationsproblem im Automobilbereich, welcher sich ohnehin aktuell in einem aktiven Wandel befindet.

2021-08-01 13:13 UTC, Mattis94 commented on drafts/2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-bytes-nach-Hannover
> +Die Reihe von abgesagten Automobilmessen und -ausstellungen, wie z.B. der Genfer Salon, New York Autoshow und Motortec Madrid 2020 und dann 2021, bildete ein ernstes Kommunikationsproblem im Automobi
Die Peppermint Event GmbH hat diese *Problematik

ersten Mal eine komplett *digitale Messe

*30 Partner waren bei der Messe vertreten und mmmint.ai war neben DMAX, Auto Bild, TÜV Nord und Continental auch mit dabei.

2021-08-01 13:13 UTC, Mattis94 commented on drafts/2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-bytes-nach-Hannover
> +> Maximilian Stein erzählte wie mmmmint.ai mit einem digitalen Fahrzeugscanner angefangen hat, der Dokumente digitalisiert und automatisiert. Zurzeit sind wir dabei eine Kilometerstandsprognose zu en
Ich wusste gar nicht, dass wir schon einen Fahrzeugscanner haben :D

*Maximilian Stein berichtete wie mmmmint.ai mit einem Fahrzeugscheinscanner angefangen hat, der diese automatisch digitalisiert.

*Zurzeit sind wir dabei eine Kilometerstandsprognose zu entwickeln, die bei der Vorhersage von Wartungsterminen unterstützt.

*Das Ziel ist freien Werkstätten die Kaltaquise zu vereinfachen, ihnen bei der Digitalisierung unterstützend zur Seite stehen und Künstliche Intelligenz auch für kleine Handwerksbetriebe greifbarer zu machen.

2021-08-01 13:13 UTC, Mattis94 commented on drafts/2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-bytes-nach-Hannover
> +[Max Leimkühler](https://www.linkedin.com/in/maxleimkuehler/) führte einen spannenden Workshop durch zum Thema „Künstliche Intelligenz in der Werkstatt” in dem er erklärte wie künstliche Intelligenz
*... führte einen spannenden Workshop durch zum Thema „Künstliche Intelligenz in der Werkstatt”, in dem er erklärte wie künstliche Intelligenz funktioniert, was der Unterschied zwischen starker und schwacher KI ist und wie mmmint.ai diese Technologie in seine smarten Lösungen integriert.

2021-08-03 06:57 UTC, Mattis94 requested changes

2021-08-03 06:57 UTC, Mattis94 commented on drafts/2021-08-01-mmmint.ai-schickt-gleich-zwei-Founder-zur-cars-and-bytes-nach-Hannover
> +![Max Stein bei Cars&Bytes](/images/maxstein.jpg)
Hier wird auf ein Bild verwiesen, was es so nicht gibt. Fehlt das Bild noch, oder ist der Pfad einfach falsch?

2021-08-03 12:48 UTC, Mattis94 approved these changes

2021-08-03 12:48 UTC, merged