Create 2021-09-03-mmmint.ai-als-assoziierter-Partner-bei-Gaia-X-Proje…
mmmint-ai/mmmint.ai pull request #66
Opened 2021-08-21 18:07 UTC by maximilianstein

…kt.md

2021-08-22 09:28 UTC, maxleimkuehler requested changes

2021-08-22 09:28 UTC, maxleimkuehler commented on drafts/2021-09-03-mmmint.ai-als-assoziierter-Partner-bei-Gaia-X-Projekt.md
> +Die Initiative GAIA-X ist ein von Wirtschaft, Wissenschaft und Verwaltung getragenes Projekt zum Aufbau einer sicheren, leistungs- und wettbewerbsfähigen Dateninfrastruktur in Europa. Damit Projektsk
Damit Projektskizzen ... : den Satz würde ich weglassen

2021-08-22 09:28 UTC, maxleimkuehler commented on drafts/2021-09-03-mmmint.ai-als-assoziierter-Partner-bei-Gaia-X-Projekt.md
> +Die Diagnose von Fehlern in Fahrzeugen erfolgt derzeit meist über proprietäre Diagnosesysteme mittels der On-Board-Diagnose (OBD) Schnittstelle. Diese Diagnosen sind nicht immer richtig und führen hä
.. Sich einfach in den ... integrieren lässt.

2021-08-22 15:42 UTC, maximilianstein reviewed
Umgeschrieben von Max L.

2021-08-23 06:09 UTC, Mattis94 commented
@maximilianstein  Typos sind angepasst, das Ding kann jetzt eigentlich so gemerged werden.

2021-08-23 06:09 UTC, Mattis94 approved these changes

2021-08-23 11:43 UTC, merged